### ISSUE TITLE
Set up coveralls code coverage reporting

### ISSUE THREAD

**Issue by psigen** [personalrobotics/aikido#25]
@jslee02 recently set up code-coverage auditing for DART in https://github.com/dartsim/dart/pull/632.  I think it makes sense to have here as well, since we would like to have the same high-quality code in `aikido`.

@jslee02 and @mkoval: can we make this happen?

**Comment by mkoval** [comment]
I have `coveralls` running on Travis now after *a lot* of fiddling with `catkin build`. Our `.travis.yml` file is not pretty, but it works. 😰 

Unfortunately, the JSON file upload fails with this error message:
```
{"message":"Couldn't find a repository matching this job.","error":true}
```

I thought this was happening because we were using travis-ci.com (for private repositories) instead of travis-ci.org (for public repositories); see #59. However, I migrated Aikido to travis-ci.org and am seeing the same error. @jslee02 do you have any idea how to resolve this?

My best guess is that it's happening because we're building from the `feature/statespace` branch instead of the default branch (`master`). Maybe it will fix itself when we merge #32?

**Comment by jslee02** [comment]
> I thought this was happening because we were using travis-ci.com (for private repositories) instead of travis-ci.org (for public repositories); see #59.

Yeah, it's tricky. I had the same problem. The solution would be setting the coveralls token as an environment variable in `.travis.yml` as [this](https://github.com/dartsim/dart/blob/master/.travis.yml#L16) (see [this](https://github.com/JoakimSoderberg/coveralls-cmake#faq)). The coverall token for AIKIDO can be found [here](https://coveralls.io/github/personalrobotics/aikido), but I can't see the configuration page as I don't have the access maybe.

**Comment by mkoval** [comment]
Thanks for the tip @jslee02! I'm not sure why it was necessary, but setting `COVERALLS_REPO_TOKEN` fixed it.

**Comment by mkoval** [comment]
@jslee02 you may want to resolve this: https://github.com/dartsim/dart/issues/687.
